DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burger (
id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
burgerName VARCHAR (30) NOT NULL,
devoured BOOLEAN NOT NULL
);